# global settings for the project
from os import path

data_folder = 'data'
csv_encoding = "ISO-8859-1"
# files generated by prepare_data after
# combining data from various sources
combined_output_file_name = 'combined_agri_data_all.csv'
combined_output_file_name_encoded = 'combined_agri_data_encoded_all.csv'

# files generated by sanitize_data after
# removing columns and countries with insufficient data
# and filling na with nearest available data where possible
final_agri_file_name = 'agri_data_final.csv'

# files created by generate_train_test_set
train_file_name_suffix = '_train.csv'
test_file_name_suffix = '_test.csv'

# result file created by data_analysis
result_file_name = 'result.txt'

def get_data_file(file_name):
    return path.join(data_folder, file_name)